In [1]:
import torch
print(torch.__version__)  # PyTorch 버전을 출력합니다.

2.5.1


In [3]:
t1=torch.tensor([[1,1],[1,2]])
t1

tensor([[1, 1],
        [1, 2]])

In [7]:
x1=t1.numpy()
print(x1)

[[1 1]
 [1 2]]


tensor의 연산

In [8]:
a=torch.FloatTensor([[1,2],
[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])

In [12]:
print(a+b) #덧셈
print(a-b) #뺄셈
print(a*b) #곱
print(a/b) #나누기
print(a==b) #불린
print(a!=b) #!불린
print(a**b) #제곱

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])


In [13]:
#인플레이스 연산
print(a)
print(a.mul(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])


In [14]:
#값이 바뀜
print(a.mul_(b))
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
