In [121]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

In [122]:
names=['sepal-length','sepal-width','petal-length','petal-width','Class']
dataset=pd.read_csv('../data/iris.data',names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [123]:
X=dataset.values[:,:-1]
Y=dataset.values[:,-1]
#분류

In [124]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [125]:
X_train[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [5.5, 2.5, 4.0, 1.3],
       [5.4, 3.0, 4.5, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.9, 3.1, 4.9, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 3.0, 4.5, 1.5],
       [5.7, 2.5, 5.0, 2.0],
       [6.7, 3.1, 4.7, 1.5]], dtype=object)

In [126]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
X_train=s.fit_transform(X_train)
X_test=s.fit_transform(X_test)
print(X_train[0:5])
print(X_test[0:5])

[[-0.93037174  0.96720048 -1.33878306 -1.29973604]
 [-0.4428407  -1.33109769  0.1304407   0.121682  ]
 [-0.56472346 -0.18194861  0.41298373  0.38012164]
 [-1.17413726  0.04788121 -1.28227445 -1.42895586]
 [-0.07719242 -0.64160824  0.75203537  1.54310004]]
[[ 0.99646335  0.11529763  0.39897693  0.32654514]
 [-0.90912393 -2.35536584 -0.12650488 -0.24135945]
 [ 0.75826494 -0.13176872  0.34059006  0.18456899]
 [ 0.04366971 -0.62590141  0.80768501  1.03642587]
 [ 0.16276891  0.11529763  0.80768501  0.89444973]]


In [127]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=50)

In [128]:
from sklearn.metrics import accuracy_score
y_pred=knn.predict(X_test)
print('정확도:{}'.format(accuracy_score(y_test,y_pred)))

정확도:0.9333333333333333


In [129]:
print(y_pred[0:10])
print(y_test[0:10])

['Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica']
['Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica']


In [130]:
k=50

acc_array=np.zeros(k)
for i in np.arange(1,k+1,1):
  classifier=KNeighborsClassifier(n_neighbors=i).fit(X_train,y_train)
  y_pred=classifier.predict(X_test)
  acc=metrics.accuracy_score(y_test,y_pred)
  acc_array[i-1]=acc
  
max_acc=np.amax(acc_array)
acc_list=list(acc_array)
k=acc_list.index(max_acc)
print(acc_list)
print('정확도 {}으로 최적의 K는 {}입니다'.format(max_acc,k+1))



[np.float64(0.9333333333333333), np.float64(0.9333333333333333), np.float64(0.9333333333333333), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9333333333333333), np.float64(0.9666666666666667), np.float64(0.9333333333333333), np.float64(0.9666666666666667), np.float64(0.9333333333333333), np.float64(0.9666666666666667), np.float64(0.9333333333333333), np.float64(0.9333333333333333), np.float64(0.9333333333333333), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.float64(0.9666666666666667), np.floa

SVM

In [131]:
#! pip install tensorflow

In [132]:
from sklearn import svm
from sklearn import metrics
from sklearn import datasets
from sklearn import model_selection

import tensorflow as tf

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'

In [133]:
iris=datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [134]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(iris.data,iris.target,test_size=0.5,random_state=33)

In [135]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(75, 4) (75,) (75, 4) (75,)


In [136]:
svm=svm.SVC(kernel='linear',C=1.0, gamma=0.5)
svm.fit(x_train, y_train)
prediction=svm.predict(x_test)
score=metrics.accuracy_score(y_test, prediction)
print('정확도:{0:f}'.format(score))

정확도:0.986667


In [137]:
import pandas as pd

In [138]:
df = pd.read_csv('../data/titanic_train.csv', index_col='PassengerId')
print(df.head())

             Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S

[5 rows x 11 columns]


In [139]:
df=df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1}) # 성별을 0과 1로 변환
df = df.dropna() # 결측치가 있는 행을 제거
X = df.drop('Survived', axis=1) # 'Survived' 열을 제외한 모든 열
y = df['Survived'] # 'Survived' 열
y # dataframe에서 하나의 값은 series로 반환

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
886    0
887    0
888    1
890    1
891    0
Name: Survived, Length: 714, dtype: int64

In [140]:
df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 1 to 891
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    714 non-null    int64  
 1   Sex       714 non-null    int64  
 2   Age       714 non-null    float64
 3   SibSp     714 non-null    int64  
 4   Parch     714 non-null    int64  
 5   Fare      714 non-null    float64
 6   Survived  714 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 44.6 KB


In [141]:
# train, test 데이터 나누기

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [142]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


(535, 6) (179, 6) (535,) (179,)


In [143]:
from sklearn import tree
model=tree.DecisionTreeClassifier() # 의사결정트리 모델을 사용
model.fit(X_train,y_train) 

# 예측 결과 출력

DecisionTreeClassifier()

In [144]:
y_predict = model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict) # 정확도를 출력

0.8212290502793296

In [145]:
from sklearn.metrics import confusion_matrix
pd.DataFrame(
    confusion_matrix(y_test, y_predict),
    columns=['Predicted Not Survival', 'Predicted Survival'],
    index=['True Not Survival', 'True Survival']
)

Predicted Not Survival  Predicted Survival
True Not Survival                      97                  15
True Survival                          17                  50