In [1]:
import torch
import torch.nn.functional as F

In [3]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z,dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [7]:
z=torch.rand(3,5,requires_grad=True)
print(z)
y_hat=F.softmax(z,dim=1)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.5905, 0.4853, 0.2014, 0.0306, 0.4401],
        [0.6628, 0.7576, 0.7691, 0.2571, 0.3366],
        [0.2386, 0.3183, 0.1332, 0.3206, 0.8843]], requires_grad=True)
tensor([[0.2494, 0.2245, 0.1690, 0.1425, 0.2146],
        [0.2174, 0.2390, 0.2418, 0.1449, 0.1569],
        [0.1673, 0.1812, 0.1506, 0.1816, 0.3192]], grad_fn=<SoftmaxBackward0>)
tensor([1., 1., 1.], grad_fn=<SumBackward1>)


In [28]:
y=torch.randint(5,(3,)).long()
print(y)
print(y_hat)
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot)
print(y.unsqueeze(1))
y_one_hot.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot)

tensor([3, 3, 1])
tensor([[0.2494, 0.2245, 0.1690, 0.1425, 0.2146],
        [0.2174, 0.2390, 0.2418, 0.1449, 0.1569],
        [0.1673, 0.1812, 0.1506, 0.1816, 0.3192]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[3],
        [3],
        [1]])
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.]])


In [29]:
import torch.nn as nn
import torch.optim as optim

In [30]:
torch.manual_seed(1)
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]

In [32]:
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [35]:
y_one_hot=torch.zeros(8,3)
print(y_one_hot)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [36]:
w=torch.zeros((4,3),requires_grad=True)
b=torch.zeros((1,3),requires_grad=True)
print(w)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [37]:
optimizer=optim.SGD([w,b],lr=0.1)
epochs=10001

In [38]:
for epoch in range(epochs):
  y_hat=F.softmax(x_train.matmul(w)+b, dim=1)
  cost=(y_one_hot*-torch.log(y_hat)).sum(dim=1).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print(epoch, cost.item())

0 1.0986123085021973
100 0.7041994333267212
200 0.6229995489120483
300 0.5657169222831726
400 0.515291154384613
500 0.46766161918640137
600 0.42127782106399536
700 0.3754016160964966
800 0.3297656774520874
900 0.2850725054740906
1000 0.24815456569194794
1100 0.2326759546995163
1200 0.22139865159988403
1300 0.2111290842294693
1400 0.2017364799976349
1500 0.1931132972240448
1600 0.18516956269741058
1700 0.17782922089099884
1800 0.17102716863155365
1900 0.16470736265182495
2000 0.15882113575935364
2100 0.15332652628421783
2200 0.14818628132343292
2300 0.14336803555488586
2400 0.1388428658246994
2500 0.13458551466464996
2600 0.13057351112365723
2700 0.126786470413208
2800 0.12320646643638611
2900 0.11981712281703949
3000 0.11660405248403549
3100 0.1135539561510086
3200 0.11065515130758286
3300 0.10789669305086136
3400 0.10526889562606812
3500 0.10276281088590622
3600 0.10037028789520264
3700 0.09808402508497238
3800 0.09589695185422897
3900 0.0938030257821083
4000 0.09179661422967911
4100 

In [40]:
y_hat=F.softmax(x_train.matmul(w)+b,dim=1)
print(y_hat)
print(y_one_hot)

tensor([[7.9508e-11, 6.5691e-06, 9.9999e-01],
        [1.7810e-04, 1.9474e-02, 9.8035e-01],
        [1.1670e-13, 4.1809e-02, 9.5819e-01],
        [6.1377e-10, 9.6248e-01, 3.7520e-02],
        [7.2622e-02, 9.2453e-01, 2.8516e-03],
        [3.8537e-02, 9.6146e-01, 7.0806e-08],
        [9.1229e-01, 8.7705e-02, 8.1009e-08],
        [9.9212e-01, 7.8798e-03, 5.7660e-11]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [41]:
for y in y_hat:
  print(y.argmax().item())

2
2
2
1
1
1
0
0


In [43]:
import sklearn.datasets as datasets
iris=datasets.load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [44]:
x_train=torch.FloatTensor(iris.data)
y_train=torch.LongTensor(iris.target)
print(x_train.size())
print(y_train.size())

torch.Size([150, 4])
torch.Size([150])
