In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)
  def forward(self,x):
    return self.linear(x)

In [6]:
model=LinearRegressionModel()
print(model)
optimizer=optim.SGD(model.parameters(),lr=0.01)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [7]:
epochs=2001

for epoch in range(epochs):
  y=model(x_data)
  cost=F.mse_loss(y,t_data)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print(epoch, cost.item(),list(model.parameters()))

0 102.39723205566406 [Parameter containing:
tensor([[-0.2703]], requires_grad=True), Parameter containing:
tensor([0.7842], requires_grad=True)]
100 0.013698798604309559 [Parameter containing:
tensor([[1.9243]], requires_grad=True), Parameter containing:
tensor([1.2734], requires_grad=True)]
200 0.006958608515560627 [Parameter containing:
tensor([[1.9460]], requires_grad=True), Parameter containing:
tensor([1.1949], requires_grad=True)]
300 0.0035347312223166227 [Parameter containing:
tensor([[1.9615]], requires_grad=True), Parameter containing:
tensor([1.1389], requires_grad=True)]
400 0.001795515650883317 [Parameter containing:
tensor([[1.9726]], requires_grad=True), Parameter containing:
tensor([1.0990], requires_grad=True)]
500 0.000912061776034534 [Parameter containing:
tensor([[1.9805]], requires_grad=True), Parameter containing:
tensor([1.0705], requires_grad=True)]
600 0.00046330917393788695 [Parameter containing:
tensor([[1.9861]], requires_grad=True), Parameter containing:
te

In [9]:
print(model(torch.FloatTensor([7])))

tensor([14.9996], grad_fn=<ViewBackward0>)


In [18]:
#data활용
import pandas as pd
df=pd.read_csv('../data/data-01-test-score.csv', header=None)
x_data=df.values[:,:-1]
t_data=df.values[:,-1]
print(x_data.shape, t_data.shape)
t_data=t_data.reshape(-1, 1)
print(x_data.shape, t_data.shape)
print(type(x_data), type(t_data))

x_data1=torch.from_numpy(x_data)
t_data1=torch.from_numpy(t_data)
print(type(x_data1), type(t_data1))

indim=x_data1.size(1)
print(indim)




(25, 3) (25,)
(25, 3) (25, 1)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>
3


In [21]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(indim,1)

    def forward(self, x):
        return self.linear(x)